export const LOGIN_USER_START ="LOGIN_USER_START";
export const LOGIN_USER_SUCCESS ="LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE ="LOGIN_USER_FAILURE";

export const REGISTER_USER_START ="REGISTER_USER_START";
export const REGISTER_USER_SUCCESS ="REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE ="REGISTER_USER_FAILURE";

export const NOW_PLAYING_START ="NOW_PLAYING_START";
export const NOW_PLAYING_SUCCESS ="NOW_PLAYING_SUCCESS";
export const NOW_PLAYING_FAILURE ="NOW_PLAYING_FAILURE";


export const POPULAR_START ="POPULAR_START";
export const POPULAR_SUCCESS ="POPULAR_SUCCESS";
export const POPULAR_FAILURE ="POPULAR_FAILURE";

export const TOP_START ="TOP_START";
export const TOP_SUCCESS ="TOP_SUCCESS";
export const TOP_FAILURE ="TOP_FAILURE";


export const UPCOMMING_START ="UPCOMMING_START";
export const UPCOMMING_SUCCESS ="UPCOMMING_SUCCESS";
export const UPCOMMING_FAILURE ="UPCOMMING_FAILURE";

export const SEARCH_START ="SEARCH_START";
export const SEARCH_SUCCESS ="SEARCH_SUCCESS";
export const SEARCH_FAILURE ="SEARCH_FAILURE";


export const MOVIES_BY_ID_START ="MOVIES_BY_ID_START";
export const MOVIES_BY_ID_SUCCESS ="MOVIES_BY_ID_SUCCESS";
export const MOVIES_BY_ID_FAILURE ="MOVIES_BY_ID_FAILURE";


export const MOVIES_ID = "MOVIES_ID";
export const OPEN = "OPEN";
export const TOGGLE = "TOGGLE";